### ISSUE TITLE
Panics on sleep/wake

### ISSUE THREAD

**Issue by robbles** [skelterjohn/rerun#29]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x77678]

goroutine 1 [running]:
panic(0x1a6460, 0x820340100)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
github.com/howeyc/fsnotify.(*Watcher).removeWatch(0x8207ba000, 0x8208f3700, 0x3b, 0x0, 0x0)
	/Users/rob/go/src/github.com/howeyc/fsnotify/fsnotify_bsd.go:269 +0x878
github.com/howeyc/fsnotify.(*Watcher).Close(0x8207ba000, 0x0, 0x0)
	/Users/rob/go/src/github.com/howeyc/fsnotify/fsnotify_bsd.go:128 +0x1ac
main.rerun(0x7fff5fbfee60, 0x27, 0x8203382d0, 0x0, 0x0, 0x0, 0x0)
	/Users/rob/go/src/github.com/skelterjohn/rerun/rerun.go:226 +0x7ad
main.main()
	/Users/rob/go/src/github.com/skelterjohn/rerun/rerun.go:283 +0x289
```

It looks like this happens only on sleep/wake, as I've noticed it every time I leave rerun up and re-open my laptop.

Possibly a signal is being passed that's missing some attributes? Or a unexpected signal? This is not a big deal for my use case, but I thought I'd report it anyways.

**Comment by skelterjohn** [comment]
I think the real answer here is to migrate to https://github.com/fsnotify/fsnotify, but I'm not sure when I'll find time to do that.

Thanks for the report, hopefully someone sees this and makes a PR :)
